version: '3.9'

services:
  cardano-rewards:
    restart: always
    image: cardano-rewards-${NETWORK}
    build:
      context: .
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SERVER_PORT=${SERVER_PORT}
      - NETWORK=${NETWORK}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
      - REWARD_LIST_SIZE_EACH_THREAD=${REWARD_LIST_SIZE_EACH_THREAD}
      - EPOCH_STAKE_LIST_SIZE_EACH_THREAD=${EPOCH_STAKE_LIST_SIZE_EACH_THREAD}
      - POOL_INFO_LIST_SIZE_EACH_THREAD=${POOL_INFO_LIST_SIZE_EACH_THREAD}
      - POOL_MAX_SIZE=${POOL_MAX_SIZE}
      - POOL_CORE_SIZE=${POOL_CORE_SIZE}
      - FLYWAY_ENABLE=${FLYWAY_ENABLE}
      - FLYWAY_VALIDATE=${FLYWAY_VALIDATE}
      - POOL_INFO_DATA_JOB_ENABLED=${POOL_INFO_DATA_JOB_ENABLED}
      - FETCH_AND_SAVE_POOL_INFO_DATA_DELAY=${FETCH_AND_SAVE_POOL_INFO_DATA_DELAY}
      - KOIOS_BASE_URL_ENABLED=${KOIOS_BASE_URL_ENABLED}
      - KOIOS_BASE_URL=${KOIOS_BASE_URL}
      - KOIOS_AUTH_TOKEN=${KOIOS_AUTH_TOKEN}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
