version: '3.9'

services:
  cardano-rewards:
    restart: always
    image: cardano-rewards-${NETWORK}
    build:
      context: .
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SERVER_PORT=${SERVER_PORT}
      - NETWORK=${NETWORK}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
      - LIST_SIZE_EACH_THREAD=${LIST_SIZE_EACH_THREAD}
      - POOL_MAX_SIZE=${POOL_MAX_SIZE}
      - POOL_CORE_SIZE=${POOL_CORE_SIZE}
      - FLYWAY_ENABLE=${FLYWAY_ENABLE}
      - FLYWAY_VALIDATE=${FLYWAY_VALIDATE}
