# Infrastructure domain
infrastructure:
  host: ${HOST:localhost}
spring:
  # Datasource specific configs
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${infrastructure.host}:${POSTGRES_PORT:5432}/${POSTGRES_DB:explorer}?currentSchema=${spring.jpa.properties.hibernate.default_schema}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:1}
    driver-class-name: org.postgresql.Driver
    # Hikari specific configs
    hikari:
      pool-name: explorer-api-pool
      minimum-idle: 1 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 10 #maximum pool size
      idle-timeout: 300000 #maximum idle time for connection
      max-lifetime: 900000 #maximum lifetime in milliseconds of a connection in the pool after it is closed.
      connection-timeout: 50000 #maximum number of milliseconds that a client will wait for a connection
      auto-commit: false #default auto-commit behavior.
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  # JPA specific configs
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${POSTGRES_SCHEMA:mainnet}
        show_sql: false
        format_sql: true
        jdbc:
          batch_size: 100
  task:
    execution:
      pool:
        max-size: 2
        core-size: 2
        queue-capacity: 50
      thread-name-prefix: Executorxx-

logging:
  level:
    com:
      cardano: INFO
    io: OFF
    root: INFO

jobs:
  koios:
    enabled: ${KOIOS_JOB_ENABLED:true}
    insert:
      delay: ${INSERT_KOIOS_DELAY:180000}
      init: 5000
  install-batch: 100
token:
  metadata:
    url: ${TOKEN-METDATA-URL:https://github.com/cardano-foundation/cardano-token-registry.git}
    folder: ${TOKEN-METADATA-FOLDER:/mappings}
application:
  network: ${NETWORK_NAME:mainnet}

kafka:
  auto-create-topics: false
  admin:
    bootstrapServers: ${BOOSTRAP_SERVER_HOST:localhost}:${BOOSTRAP_SERVER_PORT:29092}
  producers:
    json-producer:
      clientId: json-producer
      retries: 3
      bootstrapServers: ${BOOSTRAP_SERVER_HOST:localhost}:${BOOSTRAP_SERVER_PORT:29092}
      maxInFlightRequestsPerConnection: 1
      requestTimeoutMs: 30000
      batchSize: 16384
      lingerMs: 5
      bufferMemory: 33554432
      acks: all
      enableIdempotence: true
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer
  consumers:
    json-consumer:
      clientId: json-consumer
      bootstrapServers: ${BOOSTRAP_SERVER_HOST:localhost}:${BOOSTRAP_SERVER_PORT:29092}
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      autoOffsetReset: earliest
      enableAutoCommit: false
      autoCommitIntervalMs: 1000
      sessionTimeoutMs: 30000
      trustedPackages: "*"
      allowAutoCreateTopics: false
      concurrency: 6
      pollTimeout: 360000000
      groupId: ${NETWORK_NAME:preprod}
koios:
  network: ${KOIOS_NETWORK:mainet}
  reward:
    fixed-thread-pool-size: ${FIXED_THEAD_POOL_SIZE:20}
    list-size-each-thread: ${LIST_SIZE_EACH_THREAD:5}